/**
 * Warp Split Fork Extension
 *
 * Slash commands:
 * - /warp-pane-fork [optional prompt]
 * - /warp-tab-fork [optional prompt]
 *
 * Forks the current Pi session into Warp. `/warp-pane-fork` is an experimental
 * macOS UI automation workaround that presses Cmd+D in Warp, pastes the forked
 * Pi command into the new pane, and restores the clipboard. `/warp-tab-fork`
 * opens a new named Warp tab through a generated `warp://tab_config/...` URL.
 */

import type { ExtensionAPI, ExtensionCommandContext } from "@earendil-works/pi-coding-agent";
import { randomUUID } from "node:crypto";
import { existsSync, promises as fs, readFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";

const GENERATED_CONFIG_MARKER = "# Generated by pi-agent-toolkit dotfiles/extensions/warp-split-fork.ts.";
const CONFIG_STEM = "pi_agent_toolkit_warp_split_fork";
const DEFAULT_TAB_TITLE = "Pi Fork";
const PROMPT_TITLE_PREFIX = "Pi: ";
const PROMPT_TITLE_MAX_LENGTH = 40;

type ParentFlagSpec = { takesValue: boolean };

const FORWARDED_PARENT_FLAGS = new Map<string, ParentFlagSpec>([
  ["--provider", { takesValue: true }],
  ["--model", { takesValue: true }],
  ["--system-prompt", { takesValue: true }],
  ["--append-system-prompt", { takesValue: true }],
  ["--models", { takesValue: true }],
  ["--tools", { takesValue: true }],
  ["-t", { takesValue: true }],
  ["--thinking", { takesValue: true }],
  ["--extension", { takesValue: true }],
  ["-e", { takesValue: true }],
  ["--skill", { takesValue: true }],
  ["--prompt-template", { takesValue: true }],
  ["--theme", { takesValue: true }],
  ["--agent-mode", { takesValue: true }],
  ["--mcp-config", { takesValue: true }],
  ["--no-tools", { takesValue: false }],
  ["-nt", { takesValue: false }],
  ["--no-builtin-tools", { takesValue: false }],
  ["-nbt", { takesValue: false }],
  ["--no-extensions", { takesValue: false }],
  ["-ne", { takesValue: false }],
  ["--no-skills", { takesValue: false }],
  ["-ns", { takesValue: false }],
  ["--no-prompt-templates", { takesValue: false }],
  ["-np", { takesValue: false }],
  ["--no-themes", { takesValue: false }],
  ["--no-context-files", { takesValue: false }],
  ["-nc", { takesValue: false }],
  ["--verbose", { takesValue: false }],
  ["--offline", { takesValue: false }],
  ["--session-control", { takesValue: false }],
]);

const EXCLUDED_VALUE_FLAGS = new Set([
  // Do not paste API keys into the child shell command, even if the parent was
  // started with one. Prefer auth storage or environment variables for secrets.
  "--api-key",
  "--mode",
  "--session",
  "--fork",
  "--session-dir",
  "--export",
  "--control-session",
  "--send-session-message",
  "--send-session-mode",
  "--send-session-wait",
]);

const EXCLUDED_OPTIONAL_VALUE_FLAGS = new Set(["--print", "-p", "--list-models"]);

const WARP_PANE_FORK_SCRIPT = `on run argv
	set commandText to item 1 of argv
	set previousClipboard to missing value
	try
		set previousClipboard to the clipboard
	end try

	try
		tell application "Warp" to activate
		delay 0.25
		tell application "System Events"
			tell process "Warp"
				keystroke "d" using command down
				delay 0.8
				set the clipboard to commandText
				delay 0.1
				keystroke "v" using command down
				delay 0.25
				key code 36
				delay 0.2
			end tell
		end tell
	on error errorMessage number errorNumber
		try
			if previousClipboard is not missing value then set the clipboard to previousClipboard
		end try
		error errorMessage number errorNumber
	end try

	try
		if previousClipboard is not missing value then set the clipboard to previousClipboard
	end try
end run`;

function shellQuote(value: string): string {
  if (value.length === 0) return "''";
  return `'${value.replace(/'/g, `'"'"'`)}'`;
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function getPiInvocationParts(): string[] {
  const currentScript = process.argv[1];
  if (currentScript && existsSync(currentScript)) {
    return [process.execPath, currentScript];
  }

  const execName = path.basename(process.execPath).toLowerCase();
  const isGenericRuntime = /^(node|bun)(\.exe)?$/.test(execName);
  if (!isGenericRuntime) {
    return [process.execPath];
  }

  return ["pi"];
}

function splitLongFlag(argument: string): { flag: string; hasInlineValue: boolean } {
  if (!argument.startsWith("--")) {
    return { flag: argument, hasInlineValue: false };
  }

  const equalsIndex = argument.indexOf("=");
  if (equalsIndex === -1) {
    return { flag: argument, hasInlineValue: false };
  }

  return { flag: argument.slice(0, equalsIndex), hasInlineValue: true };
}

function hasFollowingValue(args: string[], index: number): boolean {
  const next = args[index + 1];
  return next !== undefined && !next.startsWith("-") && !next.startsWith("@");
}

function getForwardedParentArgs(args: string[] = process.argv.slice(2)): string[] {
  const forwarded: string[] = [];

  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index];
    const { flag, hasInlineValue } = splitLongFlag(argument);
    const spec = FORWARDED_PARENT_FLAGS.get(flag);

    if (spec) {
      forwarded.push(argument);
      if (spec.takesValue && !hasInlineValue && index + 1 < args.length) {
        forwarded.push(args[index + 1]);
        index += 1;
      }
      continue;
    }

    if (EXCLUDED_VALUE_FLAGS.has(flag) && !hasInlineValue && index + 1 < args.length) {
      index += 1;
      continue;
    }

    if (EXCLUDED_OPTIONAL_VALUE_FLAGS.has(flag) && !hasInlineValue && hasFollowingValue(args, index)) {
      index += 1;
    }
  }

  return forwarded;
}

function buildPiCommandParts(sessionFile: string | undefined, prompt: string): string[] {
  const commandParts = [...getPiInvocationParts(), ...getForwardedParentArgs()];

  if (sessionFile) {
    commandParts.push("--session", sessionFile);
  }

  if (prompt.length > 0) {
    commandParts.push(prompt);
  }

  return commandParts;
}

function buildPiCommand(sessionFile: string | undefined, prompt: string): string {
  return buildPiCommandParts(sessionFile, prompt).map(shellQuote).join(" ");
}

function buildShellStartupCommand(cwd: string, sessionFile: string | undefined, prompt: string): string {
  return ["cd", shellQuote(cwd), "&&", ...buildPiCommandParts(sessionFile, prompt).map(shellQuote)].join(" ");
}

function containsDisallowedTitleCharacter(title: string): boolean {
  for (let index = 0; index < title.length; index += 1) {
    const code = title.charCodeAt(index);
    if (code < 32 || code === 127) {
      return true;
    }
  }

  return Array.from(title).some((character) => character !== " " && character.trim() === "");
}

function validateTitle(title: string): void {
  if (containsDisallowedTitleCharacter(title)) {
    throw new Error("Warp tab title cannot contain control or non-space whitespace characters");
  }

  if (title.includes("{{") || title.includes("}}")) {
    throw new Error("Warp tab title cannot contain Handlebars template delimiters");
  }
}

function compactWhitespace(value: string): string {
  return value.trim().replace(/\s+/g, " ");
}

function truncateTitle(value: string): string {
  if (value.length <= PROMPT_TITLE_MAX_LENGTH) {
    return value;
  }

  return `${value.slice(0, PROMPT_TITLE_MAX_LENGTH - 1)}…`;
}

function titleFromPrompt(prompt: string): string {
  const compactPrompt = compactWhitespace(prompt);
  if (!compactPrompt) {
    return DEFAULT_TAB_TITLE;
  }

  return truncateTitle(`${PROMPT_TITLE_PREFIX}${compactPrompt}`);
}

function isGeneratedConfig(content: string): boolean {
  return content.startsWith(GENERATED_CONFIG_MARKER);
}

function generatedConfigPath(): string {
  const configDir = path.join(os.homedir(), ".warp", "tab_configs");
  const defaultPath = path.join(configDir, `${CONFIG_STEM}.toml`);

  if (!existsSync(defaultPath)) {
    return defaultPath;
  }

  const existing = readFileSync(defaultPath, "utf8");
  if (isGeneratedConfig(existing)) {
    return defaultPath;
  }

  return path.join(configDir, `${CONFIG_STEM}_${Date.now()}.toml`);
}

function buildSinglePaneConfig({ cwd, command, title }: { cwd: string; command: string; title: string }): string {
  return `${GENERATED_CONFIG_MARKER}
# Single terminal tab generated by the Pi /warp-tab-fork extension.

name = ${tomlString(title)}
title = ${tomlString(title)}

[[panes]]
id = "main"
type = "terminal"
directory = ${tomlString(cwd)}
is_focused = true
commands = [${tomlString(command)}]
`;
}

function buildTabConfigUrl(configPath: string): string {
  const configStem = path.basename(configPath, ".toml");
  return `warp://tab_config/${encodeURIComponent(configStem)}`;
}

async function writeWarpConfig(content: string): Promise<string> {
  const configPath = generatedConfigPath();
  await fs.mkdir(path.dirname(configPath), { recursive: true });
  await fs.writeFile(configPath, content, "utf8");
  return configPath;
}

function formatLaunchFailure(errorOutput: string): string {
  if (/not allowed assistive access|not authorized|accessibility|system events/i.test(errorOutput)) {
    return `${errorOutput}\nGrant Accessibility permission to Warp, your terminal app, or the app running Pi in System Settings > Privacy & Security > Accessibility.`;
  }

  return errorOutput;
}

function notifyForkedSessionPath(ctx: ExtensionCommandContext, forkedSessionFile: string | undefined): void {
  if (forkedSessionFile) {
    ctx.ui.notify(`Forked session was created: ${forkedSessionFile}`, "info");
  }
}

async function createForkedSession(ctx: ExtensionCommandContext): Promise<string | undefined> {
  const sessionFile = ctx.sessionManager.getSessionFile();
  if (!sessionFile) {
    return undefined;
  }

  const sessionDir = path.dirname(sessionFile);
  const branchEntries = ctx.sessionManager.getBranch();
  const currentHeader = ctx.sessionManager.getHeader();

  const timestamp = new Date().toISOString();
  const fileTimestamp = timestamp.replace(/[:.]/g, "-");
  const newSessionId = randomUUID();
  const newSessionFile = path.join(sessionDir, `${fileTimestamp}_${newSessionId}.jsonl`);

  const newHeader = {
    type: "session",
    version: currentHeader?.version ?? 3,
    id: newSessionId,
    timestamp,
    cwd: currentHeader?.cwd ?? ctx.cwd,
    parentSession: sessionFile,
  };

  const lines = [JSON.stringify(newHeader), ...branchEntries.map((entry) => JSON.stringify(entry))].join("\n") + "\n";

  await fs.mkdir(sessionDir, { recursive: true });
  await fs.writeFile(newSessionFile, lines, "utf8");

  return newSessionFile;
}

export default function warpSplitForkExtension(pi: ExtensionAPI): void {
  pi.registerCommand("warp-pane-fork", {
    description:
      "Experimentally fork this session into a new pane in the current Warp tab. Usage: /warp-pane-fork [optional prompt]",
    handler: async (args, ctx) => {
      if (process.platform !== "darwin") {
        ctx.ui.notify("/warp-pane-fork currently requires macOS UI automation.", "warning");
        return;
      }

      const wasBusy = !ctx.isIdle();
      const prompt = args.trim();
      const forkedSessionFile = await createForkedSession(ctx);
      const command = buildShellStartupCommand(ctx.cwd, forkedSessionFile, prompt);

      const result = await pi.exec("osascript", ["-e", WARP_PANE_FORK_SCRIPT, "--", command]);
      if (result.code !== 0) {
        const rawReason = result.stderr?.trim() || result.stdout?.trim() || "unknown osascript error";
        ctx.ui.notify(`Failed to launch Warp pane: ${formatLaunchFailure(rawReason)}`, "error");
        notifyForkedSessionPath(ctx, forkedSessionFile);
        return;
      }

      if (forkedSessionFile) {
        const fileName = path.basename(forkedSessionFile);
        const suffix = prompt ? " and sent prompt" : "";
        ctx.ui.notify(`Forked to ${fileName} in a new Warp pane${suffix}.`, "info");
        if (wasBusy) {
          ctx.ui.notify("Forked from current committed state (in-flight turn continues in original session).", "info");
        }
      } else {
        ctx.ui.notify("Opened a new Warp pane (no persisted session to fork).", "warning");
      }
    },
  });

  pi.registerCommand("warp-tab-fork", {
    description: "Fork this session into a new named Warp tab. Usage: /warp-tab-fork [optional prompt]",
    handler: async (args, ctx) => {
      if (process.platform !== "darwin") {
        ctx.ui.notify("/warp-tab-fork currently requires macOS and Warp's URL handler.", "warning");
        return;
      }

      const wasBusy = !ctx.isIdle();
      const prompt = args.trim();
      const title = titleFromPrompt(prompt);

      try {
        validateTitle(title);
      } catch (error) {
        ctx.ui.notify(error instanceof Error ? error.message : "Invalid Warp tab title", "error");
        return;
      }

      const forkedSessionFile = await createForkedSession(ctx);
      const command = buildPiCommand(forkedSessionFile, prompt);
      const configContent = buildSinglePaneConfig({ cwd: ctx.cwd, command, title });
      const configPath = await writeWarpConfig(configContent);
      const url = buildTabConfigUrl(configPath);

      const result = await pi.exec("open", [url]);
      if (result.code !== 0) {
        const reason = result.stderr?.trim() || result.stdout?.trim() || "unknown open error";
        ctx.ui.notify(`Failed to launch Warp tab: ${reason}`, "error");
        notifyForkedSessionPath(ctx, forkedSessionFile);
        return;
      }

      if (forkedSessionFile) {
        const fileName = path.basename(forkedSessionFile);
        const suffix = prompt ? " and sent prompt" : "";
        ctx.ui.notify(`Forked to ${fileName} in a new Warp tab${suffix}.`, "info");
        if (wasBusy) {
          ctx.ui.notify("Forked from current committed state (in-flight turn continues in original session).", "info");
        }
      } else {
        ctx.ui.notify("Opened a new named Warp tab (no persisted session to fork).", "warning");
      }
    },
  });
}
