import type { HandoffArtifact } from "./extractor-core.ts";

export function renderHandoffMarkdown(handoff: HandoffArtifact): string {
  const warnings = formatWarnings(handoff.warnings);
  const messages = handoff.messages.map(formatTimelineMessage).join("\n\n");

  return [
    "# Handoff Export",
    "",
    "This Markdown file is for human review. The canonical artifact for receiving agents is `handoff.json`.",
    "",
    "## Human Review Notes",
    "",
    "Review this file for private prompts, local paths, code snippets, tool output, logs, and business context before sharing.",
    "",
    "## Briefing",
    "",
    formatBriefingGenerator(handoff.briefing),
    "",
    handoff.briefing.content,
    "",
    "## Source",
    "",
    `- Agent: ${handoff.source.agent}`,
    `- Session ID: ${handoff.source.session_id ?? "null"}`,
    `- Session file: ${handoff.source.session_file ?? "null"}`,
    `- CWD: ${handoff.source.cwd}`,
    `- Generated at: ${handoff.source.generated_at}`,
    "",
    "## Preservation Policy",
    "",
    "Thinking traces are removed. Tool calls, tool results, command output, transcript text, and context summaries are preserved as handoff evidence. Extension state records that do not participate in LLM context are omitted.",
    "",
    "## Stats",
    "",
    ...Object.entries(handoff.stats).map(([key, value]) => `- ${key}: ${value}`),
    "",
    "## Warnings",
    "",
    warnings,
    "",
    "## Timeline",
    "",
    messages || "No messages written.",
    "",
  ].join("\n");
}

function formatWarnings(warnings: string[]): string {
  if (warnings.length === 0) return "None.";
  return warnings.map((warning) => `- ${warning}`).join("\n");
}

function formatBriefingGenerator(briefing: HandoffArtifact["briefing"]): string {
  if (!briefing.model) return `Generated by: ${briefing.generated_by}`;
  return `Generated by: ${briefing.generated_by} (${briefing.model})`;
}

function formatTimelineMessage(message: HandoffArtifact["messages"][number]): string {
  return [
    `### ${message.index}. ${message.role} (${message.kind})`,
    "",
    `- Source role: ${message.source_role}`,
    `- Timestamp: ${message.timestamp ?? "null"}`,
    `- Source message ID: ${message.source_message_id ?? "null"}`,
    "",
    message.content,
  ].join("\n");
}
